#!/usr/bin/env python
# coding: utf-8

# In[18]:


from sklearn.linear_model import LinearRegression
import pandas as pd


# In[12]:


train_data = pd.read_csv(r'C:\Users\kd67152\Downloads\archive\train.csv')
train_data = train_data.dropna()
test_data = pd.read_csv(r'C:\Users\kd67152\Downloads\archive\test.csv')
test_data = test_data.dropna()


# In[25]:


train_x = train_data["x"].to_numpy().reshape(-1, 1)
train_y = train_data["y"].to_numpy().reshape(-1, 1)
test_x = test_data["x"].to_numpy().reshape(-1, 1)
test_y = test_data["y"].to_numpy().reshape(-1, 1)


# In[14]:


model = LinearRegression().fit(train_x, train_y)


# In[26]:


pred_y = model.predict(test_x)


# In[16]:


def mse(x,y):
    return ((x-y)**2).mean()


# In[17]:


print(mse(pred_y, test_y))

